In [1]:
import numpy as np

In [2]:
x = np.random.random(1024)

In [4]:
print len(x)
x

1024


array([ 0.76165918,  0.58596293,  0.96834753, ...,  0.20002845,
        0.76448571,  0.43609516])

In [ ]:
import numpy as np
def DFT_slow(x):
    """Compute the discrete Fourier Transform of the 1D array x"""
    x = np.asarray(x, dtype=float)
    N = x.shape[0]
    n = np.arange(N)
    k = n.reshape((N, 1))
    M = np.exp(-2j * np.pi * k * n / N)
    return np.dot(M, x)

In [5]:
x = np.asarray(x, dtype=float)
x

array([ 0.76165918,  0.58596293,  0.96834753, ...,  0.20002845,
        0.76448571,  0.43609516])

In [6]:
x.shape[0]

1024L

In [8]:
np.arange(1024)

array([   0,    1,    2, ..., 1021, 1022, 1023])

In [10]:
np.arange(1024).reshape((1024, 1))

array([[   0],
       [   1],
       [   2],
       ..., 
       [1021],
       [1022],
       [1023]])